services:
  postgres:
    image: "bitnami/postgresql:latest"
    ports:
      - "5437:5432"
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: HelpDesk
